### ISSUE TITLE
Add CORS support to the web server

### ISSUE THREAD

**Issue by ctrl-schaff** [biothings/biothings_annotator#18]

**Comment by ctrl-schaff** [comment]
@newgene sanic has some default support for CORS out of the box. However, the extension provides a little more but I had a question about what desire for the application. This documentation can be found [here](https://sanic.dev/en/plugins/sanic-ext/http/cors.html)

Like what would be a good choice for the `CORS_ORIGINS` and do you think we'll need any of the other configuration options?

**Comment by newgene** [comment]
@ctrl-schaff start with the same setup from biothings sdk?

https://github.com/biothings/biothings.api/blob/6573562773ed66b9428aead1ba7ac187005bb031/biothings/web/handlers/base.py#L217
